version: '3.7'
services:

  yourls-app:
    image: yourls
    container_name: yourls-app
    links:
    - yourls-db
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:yourls.hostname.com
    - traefik.port=80
    - traefik.protocol=http
    - traefik.docker.network=proxy
    - traefik.backend=yourls-app
    volumes:
    - ./data/:/www/yourls
    - ./logs/:/www/logs
    - /etc/localtime:/etc/localtime:ro
    environment:
    - VIRTUAL_HOST=yourls.hostname.com
    - VIRTUAL_NETWORK=proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=yourls.hostname.com
    - LETSENCRYPT_EMAIL=user@hostname.com

    - PHP_MEMORY_LIMIT=128M
    - UPLOAD_MAX_SIZE=2G
    - APC_SHM_SIZE=128M
    - OPCACHE_MEM_SIZE=128
    - REDIS_MAX_MEMORY=64mb
    - TZ=America/Vancouver

    - DB_HOST=yourls-db
    - DB_NAME=yourls
    - DB_USER=yourls
    - DB_PASS=userpassword
 
    - SITE_NAME=sitename.com
    - ADMIN_USER=admin
    - ADMIN_PASS=selfdesign

    - DEBUG=false
    networks:
    - proxy
    - internal
    - services
    restart: always

  yourls-db:
    image: mariadb
    container_name: yourls-db
    volumes:
    - ./db:/var/lib/mysql
    - /etc/localtime:/etc/localtime:ro
    environment:
    - ROOT_PASS=password
    - DB_NAME=yourls
    - DB_USER=yourls
    - DB_PASS=userpassword
    networks:
    - internal
    - services
    restart: always

  yourls-db-backup:
    image: mysql-backup
    container_name: yourls-db-backup
    links:
    - yourls-db
    volumes:
    - ./dbbackup:/backup
    - /etc/localtime:/etc/localtime:ro
    environment:
    - DB_SERVER=yourls-db
    - DB_NAME=yourls
    - DB_USER=yourls
    - DB_PASSWORD=userpassword
    - DB_DUMP_FREQ=1440
    #- DB_DUMP_BEGIN=0000
    - DB_CLEANUP_TIME=8640
    - COMPRESSION=BZ
    networks:
    - internal
    - services
    restart: always

networks:
  proxy:
    external: true
  internal:
    external: false
  services:
    external: true

